// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/simpleChatbot.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Simplechatbot {
  public static partial class SimpleChatBotServer
  {
    static readonly string __ServiceName = "simplechatbot.SimpleChatBotServer";

    static readonly grpc::Marshaller<global::Simplechatbot.ChatRequest> __Marshaller_simplechatbot_ChatRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simplechatbot.ChatRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simplechatbot.ChatReply> __Marshaller_simplechatbot_ChatReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simplechatbot.ChatReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Simplechatbot.ChatRequest, global::Simplechatbot.ChatReply> __Method_Chat = new grpc::Method<global::Simplechatbot.ChatRequest, global::Simplechatbot.ChatReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Chat",
        __Marshaller_simplechatbot_ChatRequest,
        __Marshaller_simplechatbot_ChatReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Simplechatbot.SimpleChatbotReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SimpleChatBotServer</summary>
    [grpc::BindServiceMethod(typeof(SimpleChatBotServer), "BindService")]
    public abstract partial class SimpleChatBotServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Simplechatbot.ChatReply> Chat(global::Simplechatbot.ChatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SimpleChatBotServer</summary>
    public partial class SimpleChatBotServerClient : grpc::ClientBase<SimpleChatBotServerClient>
    {
      /// <summary>Creates a new client for SimpleChatBotServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SimpleChatBotServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SimpleChatBotServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SimpleChatBotServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SimpleChatBotServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SimpleChatBotServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Simplechatbot.ChatReply Chat(global::Simplechatbot.ChatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Chat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Simplechatbot.ChatReply Chat(global::Simplechatbot.ChatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Chat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Simplechatbot.ChatReply> ChatAsync(global::Simplechatbot.ChatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Simplechatbot.ChatReply> ChatAsync(global::Simplechatbot.ChatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Chat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SimpleChatBotServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SimpleChatBotServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SimpleChatBotServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Chat, serviceImpl.Chat).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SimpleChatBotServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Chat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Simplechatbot.ChatRequest, global::Simplechatbot.ChatReply>(serviceImpl.Chat));
    }

  }
}
#endregion
